loki:
  auth_enabled: false
  schemaConfig:
    configs:
    - from: "2020-12-11"
      index:
        period: 24h
        prefix: index_
      object_store: s3
      schema: v11
      store: boltdb-shipper
  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    type: s3
    s3:
      endpoint: ${endpoint}
      secretAccessKey: ${access_key_id}
      accessKeyId: ${access_key_id}
      insecure: true
  extraArgs:
  - "-config.expand-env=true"
  extraEnvFrom:
  - secretRef:
      name: minio-access-key

write:
  extraArgs:
  - "-config.expand-env=true"
  extraEnvFrom:
  - secretRef:
      name: minio-access-key

read:
  extraArgs:
  - "-config.expand-env=true"
  extraEnvFrom:
  - secretRef:
      name: minio-access-key

backend:
  extraArgs:
  - "-config.expand-env=true"
  extraEnvFrom:
  - secretRef:
      name: minio-access-key

test:
  enabled: false

monitoring:
  dashboards:
    enabled: true
    namespace: prometheus
  lokiCanary:
    enabled: false
