apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-observability
  namespace: istio-system
spec:
  accessLogging:
  - providers:
    - name: otel
  tracing:
  - providers:
    - name: otel-tracing
    randomSamplingPercentage: 100
