traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true

storage:
  trace:
    backend: s3
    s3:
      bucket: tempo
      endpoint: ${endpoint}
      access_key: ${access_key_id}
      secret_key: ${access_key_secret} 
      insecure: true

distributor:
  extraArgs:
  - "-config.expand-env=true"
  extraEnvFrom:
  - secretRef:
      name: minio-access-key

compactor:
  extraArgs:
  - "-config.expand-env=true"
  extraEnvFrom:
  - secretRef:
      name: minio-access-key

ingester:
  extraArgs:
  - "-config.expand-env=true"
  extraEnvFrom:
  - secretRef:
      name: minio-access-key

querier:
  extraArgs:
  - "-config.expand-env=true"
  extraEnvFrom:
  - secretRef:
      name: minio-access-key

queryFrontend:
  extraArgs:
  - "-config.expand-env=true"
  extraEnvFrom:
  - secretRef:
      name: minio-access-key

metaMonitoring:
  serviceMonitor:
    enabled: true
    labels:
      prometheus: system
